services:
    bookstore-frontend: 
        image: "${DOCKER_USERNAME}/bookstore:${GITHUB_SHA}"
        container_name: bookstore-frontend
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - /etc/nginx/ssl:/etc/nginx/ssl:ro
        restart: always

networks: 
  default: 
    external: 
      name: docker-ms
