name: CI/CD Pipeline - Bookstore Frontend

env:
  SERVICE_NAME: bookstore
  SERVICE_DIR: bookstore-frontend
  BASE_DIR: docker-microservices

on:
  push:
    branches: [ main ]
    paths:
      - 'bookstore-frontend/**'
      - '.github/workflows/bookstore-ci-cd.yml'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        working-directory: ${{ env.SERVICE_DIR }}
        run: npm ci

      - name: Build Angular app
        working-directory: ${{ env.SERVICE_DIR }}
        run: npx ng build --configuration production

      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker image
        working-directory: ${{ env.SERVICE_DIR }}
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/bookstore-frontend:${GITHUB_SHA}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Prepare directory
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: ${{ secrets.PROD_PORT }}
          script: |
            mkdir -p ~/${{ env.BASE_DIR }}

      - name: Copy docker-compose to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: ${{ secrets.PROD_PORT }}
          source: "${{ env.SERVICE_DIR }}/docker-compose.yml"
          target: "~/${{ env.BASE_DIR }}/"
  
      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: ${{ secrets.PROD_PORT }}
          envs: GITHUB_SHA
          script: | 
            cd ~/${{ env.BASE_DIR }}/${{ env.SERVICE_DIR }}
            sed -i "s|\${GITHUB_SHA}|${GITHUB_SHA}|g" docker-compose.yml
            sed -i "s|\${DOCKER_USERNAME}|${{ secrets.DOCKER_USERNAME }}|g" docker-compose.yml
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ env.SERVICE_NAME }}:${GITHUB_SHA}
            docker compose down
            docker compose up -d
