name: CI CD Pipeline - Books Service

env:
  SERVICE_NAME: books
  SERVICE_DIR: books-service
  BASE_DIR: docker-microservices

on:
  push:
    branches: [ main ]
    paths:
      - 'books-service/**'
      - '.github/workflows/books-ci-cd.yml'

jobs:
  package:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Maven Package
        working-directory: ${{ env.SERVICE_DIR }}
        run: mvn clean package --no-transfer-progress

      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker image
        working-directory: ${{ env.SERVICE_DIR }}
        run: |
          JAR_FILE=$(ls target/*.jar | head -n 1)
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/${{ env.SERVICE_NAME }}:${GITHUB_SHA}
          docker build --build-arg JAR_FILE=$JAR_FILE -t $IMAGE_NAME .
          docker push $IMAGE_NAME

  deploy:
    needs: package  
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Prepare directory
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: ${{ secrets.PROD_PORT }}
          script: |
            mkdir -p ~/${{ env.BASE_DIR }}

      - name: Copy docker-compose to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: ${{ secrets.PROD_PORT }}
          source: "${{ env.SERVICE_DIR }}/docker-compose.yml"
          target: "~/${{ env.BASE_DIR }}/"
  
      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: ${{ secrets.PROD_PORT }}
          envs: GITHUB_SHA
          script: | 
            cd ~/${{ env.BASE_DIR }}/${{ env.SERVICE_DIR }}
            sed -i "s|\${GITHUB_SHA}|${GITHUB_SHA}|g" docker-compose.yml
            sed -i "s|\${DOCKER_USERNAME}|${{ secrets.DOCKER_USERNAME }}|g" docker-compose.yml
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ env.SERVICE_NAME }}:${GITHUB_SHA}
            docker compose up -d
